name: Build all github.com/micro/examples
on:
  push: 
    branches:
      - 'release-**'
  pull_request: 
    branches:
      - 'master'

jobs:

  build:
    name: Build repos
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code examples
      uses: actions/checkout@v2
      with:
        repository: 'micro/examples'
        path: 'examples'

    - name: Build all
      run: .github/workflows/scripts/build-all-examples.sh $GITHUB_SHA
    