name: PR Sanity Check
on: 
  - push
  - pull_request
  - workflow_dispatch
jobs:
  prtest:
    name: PR sanity check
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
        cache: true
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Get dependencies
      run: |
        go install github.com/kyoh86/richgo@latest
        go get -v -t -d ./...
    - name: Run tests
      id: tests
      env:
        IN_TRAVIS_CI: yes
      run: richgo test -v -race -cover ./...
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
